"""Convert checked-in official artwork into a 1-bit C icon library and gallery.

python -m pip install --target build/brand_toolchain pillow resvg-py
python tools/build_brand_icons.py
"""
from copy import deepcopy
from hashlib import sha256
from io import BytesIO
import json
from pathlib import Path
import sys
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'build/brand_toolchain'))
from PIL import Image
import resvg_py


def main():
    assets = ROOT / 'assets/brands'
    output = ROOT / 'docs/brand-icons'
    output.mkdir(parents=True, exist_ok=True)
    ns = 'http://www.w3.org/2000/svg'
    ET.register_namespace('', ns)
    original = ET.parse(assets / 'deepseek-original.svg').getroot()
    # The official horizontal logo's last root path is its standalone whale.
    # Copy its geometry verbatim; omit the separate wordmark group.
    whale = original.findall(f'{{{ns}}}path')
    assert len(whale) == 1
    symbol = ET.Element(f'{{{ns}}}svg', {'viewBox': '0 0 56.3 41.3594', 'width': '56.3', 'height': '41.3594'})
    symbol.append(deepcopy(whale[0]))
    ET.ElementTree(symbol).write(assets / 'deepseek-symbol.svg', encoding='utf-8', xml_declaration=True)
    icons = [
        ('codex-terminal', 'Codex 官方终端 UI 图标', 'https://developers.openai.com/images/codex/icons/terminal.svg',
         'codex-terminal.svg', 'codex-terminal.svg'),
        ('deepseek', 'DeepSeek 官方鲸鱼', 'https://raw.githubusercontent.com/deepseek-ai/DeepSeek-LLM/main/images/logo.svg',
         'deepseek-original.svg', 'deepseek-symbol.svg'),
        ('openrouter', 'OpenRouter 官方 Glyph · Ink', 'https://openrouter.ai/brand/logos/transparent/glyph/svg/glyph-ink.svg',
         'openrouter.svg', 'openrouter.svg'),
    ]
    bitmaps = {size: [] for size in (24, 32, 48)}
    manifests, cards = [], []
    for name, title, url, source, symbol_file in icons:
        source_data = (assets / source).read_bytes()
        manifests.append({'name': name, 'title': title, 'url': url, 'file': source,
                          'sha256': sha256(source_data).hexdigest(), 'retrieved_on': '2026-10-06'})
        image = Image.open(BytesIO(resvg_py.svg_to_bytes(svg_path=str(assets / symbol_file), width=512))).convert('RGBA')
        # Normalize transparent canvas margins, without changing mark geometry.
        bounds = image.getchannel('A').getbbox()
        assert bounds is not None
        image = image.crop(bounds)
        sizes = []
        for size in bitmaps:
            scaled = image.copy()
            scaled.thumbnail((size - 4, size - 4), Image.Resampling.LANCZOS)
            alpha = Image.new('L', (size, size), 0)
            alpha.paste(scaled.getchannel('A'), ((size - scaled.width) // 2, (size - scaled.height) // 2))
            # Alpha threshold preserves the original silhouette without dithering.
            ink = alpha.point(lambda a: 255 if a >= 128 else 0)
            display = Image.eval(ink, lambda a: 255 - a)
            display.save(output / f'{name}-{size}.png')
            packed = bytearray(size * size // 8)
            for y in range(size):
                for x in range(size):
                    if ink.getpixel((x, y)):
                        packed[y * (size // 8) + x // 8] |= 0x80 >> (x % 8)
            assert any(packed) and len(packed) == size * size // 8
            bitmaps[size].append(packed)
            sizes.append(f'<figure><img class="pixel" src="{name}-{size}.png" width="{size * 3}" height="{size * 3}"><figcaption>{size} × {size} · {len(packed)} B</figcaption></figure>')
        cards.append(f'<article><h2>{title}</h2><p><a href="{url}">官方来源</a> · <a href="../../assets/brands/{source}">原始 SVG</a></p><div class="variants">{"".join(sizes)}</div></article>')
    header = ['// Generated by tools/build_brand_icons.py. Do not hand edit.', '#pragma once', '#include <stdint.h>', '']
    for size, items in bitmaps.items():
        header.append(f'static const uint8_t brand_bitmaps_{size}[3][{size * size // 8}] = {{')
        for (name, *_), packed in zip(icons, items):
            header.append(f'    {{ // {name}')
            for start in range(0, len(packed), 12):
                header.append('        ' + ', '.join(f'0x{b:02x}' for b in packed[start:start + 12]) + ',')
            header.append('    },')
        header.append('};\n')
    (ROOT / 'main/brand_icons_data.h').write_text('\n'.join(header), encoding='utf-8')
    (assets / 'sources.json').write_text(json.dumps(manifests, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    html = '''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>官方图标 · RLCD 图库</title><style>body{background:#eef0ed;color:#243028;font:16px system-ui;margin:0}
main{max-width:920px;margin:36px auto;padding:0 24px}p{line-height:1.8;color:#566257}article{background:white;border:1px solid #ccd4ca;border-radius:16px;padding:24px;margin:20px 0}
h1{font-size:28px}h2{font-size:20px;margin:0}a{color:#285d3e}.variants{display:flex;align-items:flex-end;gap:40px;flex-wrap:wrap}figure{margin:20px 0 0;min-width:120px}figcaption{margin-top:12px;color:#566257;font-size:14px}.pixel{image-rendering:pixelated;display:block}
</style><main><h1>官方图标 · 黑白屏图库</h1><p>官方 SVG 原文件保留在项目内，去除透明边缘后等比例缩放、居中留白，再按透明度转换为 1-bit 点阵。
下方以 3 倍尺寸展示像素效果，页面使用 24 px 版本；另提供 32 / 48 px 版本，供后续布局使用。</p>
<p>Codex 使用官方页面的终端 UI 图标，不将它标为独立品牌 Logo。DeepSeek 提取官方横标中的鲸鱼路径；OpenRouter 使用新版官方 Ink 图形。
所有品牌图形属于各自权利人。<a href="../codeck-preview/index.html">查看 Codeck 页面效果</a></p>CARDS</main></html>'''
    (output / 'index.html').write_text(html.replace('CARDS', ''.join(cards)), encoding='utf-8')
    print('Generated 9 official-source 1-bit icons (1464 bytes total) and gallery.')


if __name__ == '__main__':
    main()
